### ISSUE TITLE
Learning to use this with F Sharp

### ISSUE THREAD

**Issue by DoubleCouponDay** [machine/machine.specifications#353] opened 2018-10-01 22:57 UTC
I'm in the process of making my first test and I was wondering if there is a simpler way to ensure my required members, like `Establish` and `Because`, can implicitly comply to the required method signature. It just feels like I'm doing it wrong.

In general, getting a hello world ish mspec test working with fsharp would be very helpful.

```
[<Subject("database connection")>]
type when_connecting_to_the_database =
    static member public Subject : ApplicationDbContext = null

    member public x.setup : Establish = 
        new Establish(fun () -> ())

    member public x.context : Because =
        new Because(fun() -> ())
```

**Comment by ImaginaryDevelopment** [comment] 2018-10-09 19:37
After much experimentation, I found that this works:


```
// not required for the test to be discovered
[<Subject("database connection")>]
type when_connecting_to_the_database() =
    // must have a BehavesLike or an It type for any functionality it appears
    member val Context = Because(fun () -> printfn "Because reasons")
    member val Setup = Establish(fun () -> printfn "I was setup!")
    member val Assertion = It(fun () -> printfn "member val worked")
    // not sure about how this guy needs to be defined, but F# refuses to make public static fields
    // see http://www.ianvoyce.com/index.php/2010/10/01/public-static-fields-gone-from-f-2-0/
    static member public Subject : ApplicationDbContext = Unchecked.defaultof<_>

```

most of which was required to get the test to be discovered

**Comment by robertcoltheart** [comment] 2019-01-02 09:55
Closing as the issue is resolved

**Closed by robertcoltheart** 2019-01-02 09:55 UTC
