### ISSUE TITLE
R# Test Runner - Tests Go Missing

### ISSUE THREAD

**Issue by tapmantwo** [machine/machine.specifications#269] opened 2015-03-20 15:24 UTC
We've experienced scenarios where tests disappear from the Test Session window.  Upon investigation, it seems to happen if you have tests that inherit from some other test class, and both have a Subject attribute applied.

A simple reproduction would be as follows;

``` csharp
namespace MSpecInheritance
{
    [Subject("Some base stuff")]
    public class BaseTestClass
    {        
    }

    [Subject("Some maths")]
    public class DerivedTestClass : BaseTestClass
    {
        private static int _start;
        private static int _result;
        Establish we_have_a_starting_value_of_10 = () =>
        {
            _start = 10;
        };

        private Because we_add_5 = () => _result = _start + 5;

        private It should_equal_15 = () => _result.ShouldEqual(15);
    }
}
```

The command line runner seems fine.

**Comment by BrunoJuchli** [comment] 2015-07-01 18:09
i think this is a duplicate of #218 #221 and maybe #228

**Comment by FabianTrottmann** [comment] 2015-07-22 14:02
This bug is going to appear with every R# release again. I fixed it some time ago for R# v8, but the bug appeared again with newer versions. The subject is part of the Unit Test Element Identification of the R# runner. Tests with subjects on inherited classes disappear abruptly, because R# thinks that the subject and therefore the test changed for some reason.

**Comment by BrunoJuchli** [comment] 2015-07-22 16:07
I'm not working on it.

**Closed** 2019-01-09 03:55 UTC
Labels: Area: Runner - R#, Status: Not an issue
