### ISSUE TITLE
Machine.Specifications.Runner.VisualStudio Doesn't Support dotnet --filter 

### ISSUE THREAD

**Issue by derekgreer** [machine/machine.specifications#342] opened 2017-08-25 16:10 UTC
Machine.Specifications.Runner.VisualStudio v2.3.0 

The adaptor doesn't appear to respect anything passed to the dotnet.exe --filter parameter.

Are there any filters supported? 

Here's some examples one would expect to work:
dotnet --filer Tag!=integration
dotnet --filter Subject=component
dotnet -- filter ClassName~MySpecs

**Comment by robertcoltheart** [comment] 2019-01-09 07:01
Duplicate of #327

**Closed by robertcoltheart** 2019-01-09 07:01 UTC
Labels: Area: Runner - VS, Type: Enhancement
