### ISSUE TITLE
Behaviors not working in Rider 2020.3

### ISSUE THREAD

**Issue by neilrees** [machine/machine.specifications#424] opened 2020-12-19 10:44 UTC
Tests within a [Behavior] are not executed in Rider 2020.3.

An exception is displayed in the output:
```
--- EXCEPTION #1/1 [LoggerException]
Message = “
  TestRunner: Application  JetBrains.Rd.Tasks.RdFault: An exception was thrown while activating Machine.Specifications.Runner.ReSharper.Adapters.MspecRunner., reason: Autofac.Core.DependencyResolutionException: An exception was thrown while activating Machine.Specifications.Runner.ReSharper.Adapters.MspecRunner. ---> System.Runtime.Serialization.SerializationException: Type 'Machine.Specifications.Runner.ReSharper.Adapters.MspecRunner' in assembly 'Machine.Specifications.Runner.ReSharper.Adapters.net40, Version=2020.3.0.0, Culture=neutral, PublicKeyToken=null' is not marked as serializable.
     at System.AppDomain.CreateInstanceFromAndUnwrap(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
     at JetBrains.ReSharper.TestRunner.Extensions.AppDomainExtensions.CreateAndUnwrapFrom(AppDomain appDomain, Type type, Object[] args) in C:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\TestRunner.Utilities\Extensions\AppDomainExtensions.cs:line 37
     at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
     --- End of inner exception stack trace ---
     at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
     at Autofac.Core.Resolving.InstanceLookup.Execute()
     at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
     at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
     at JetBrains.ReSharper.TestRunner.Isolation.InAppDomainActivationBehavior.SmuggledDependencies.Create(AppDomain appDomain, IAssemblyResolver assemblyResolver, Type type, Parameter[] parameters) in C:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\TestRunner.Core\Isolation\LoadContext.Net35.cs:line 158
     at JetBrains.ReSharper.TestRunner.Isolation.LoadContext.Create(Type type, Object[] args) in C:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\TestRunner.Core\Isolation\LoadContext.Net35.cs:line 99
     at JetBrains.ReSharper.TestRunner.Implementation.TestAdapterLoadContextWrapperBase.InitializeTestExecutor() in C:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\TestRunner.Merged\Implementation\TestAdapterLoadContextWrapper.cs:line 60
     at JetBrains.ReSharper.TestRunner.Implementation.UnitTestRemoteAgent.Execute(TestRunRequest request) in C:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\TestRunner.Merged\Implementation\UnitTestRemoteAgent.cs:line 68
     at JetBrains.ReSharper.TestRunner.Implementation.ClientEndpoint.<>c__DisplayClass4_1.<TryRegisterHandler>b__1() in C:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\TestRunner.Core\Implementation\ClientEndpoint.cs:line 56
     at System.Threading.Tasks.Task`1.InnerInvoke()
     at System.Threading.Tasks.Task.Execute()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at JetBrains.ReSharper.TestRunner.Implementation.ClientEndpoint.<RunAndLog>d__10.MoveNext() in C:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\TestRunner.Core\Implementation\ClientEndpoint.cs:line 140
”
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
HResult = COR_E_APPLICATION=80131600
StackTraceString = “
  at System.Threading.Tasks.Task.Execute()
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
     at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
     at System.Threading.ThreadPoolWorkQueue.Dispatch()
”
```

For example the following tests, taken basically from the Wiki, the assertions in the behavior class do not cause test failures:
```
    public class BehaviorsTest
    {
        [Subject("Starting")]
        class When_the_car_is_started
        {
            protected static Car Subject;

            Establish context = () =>
                Subject = new Car();

            Because of = () =>
                Subject.StartEngine();


            It should_have_a_subject = () => Subject.ShouldNotBeNull();

            Behaves_like<AVehicleThatHasBeenStarted> a_vehicle_that_has_been_started;
        }

        [Subject("Starting")]
        class When_the_motorcycle_is_started
        {
            protected static Motorcycle Subject;

            Establish context = () =>
                Subject = new Motorcycle();

            Because of = () =>
                Subject.StartEngine();

            It should_have_a_subject = () => Subject.ShouldNotBeNull();

            Behaves_like<AVehicleThatHasBeenStarted> a_vehicle_that_has_been_started;
        }


        [Behaviors]
        public class AVehicleThatHasBeenStarted
        {
            protected static IVehicle Subject;

            It should_have_a_running_engine = () =>
                Subject.IsEngineRunning.ShouldBeTrue();

            It should_be_idling = () =>
                Subject.RevCount.ShouldBeGreaterThan(0);
        }
    }

    public interface IVehicle
    {
        bool IsEngineRunning { get; set; }
        int RevCount { get; set; }

        void StartEngine();
    }

    public class Car : IVehicle
    {
        public bool IsEngineRunning { get; set; }
        public int RevCount { get; set; }

        public void StartEngine()
        {
        }
    }

    public class Motorcycle : IVehicle
    {
        public bool IsEngineRunning { get; set; }
        public int RevCount { get; set; }
        public void StartEngine()
        {
        }
    }
```

The behaviors are shows as Inconclusive:
![image](https://user-images.githubusercontent.com/282424/102687436-f85c1580-41e6-11eb-85b2-77f1d37b7d86.png)

The above tests behave as expected when executed in Visual Studio 2019 16.8.3 with Resharper, and from the command line with `dotnet test`.

**Comment by robertcoltheart** [comment] 2020-12-19 12:06
Duplicate of #423 and fixed in latest release.

**Closed by robertcoltheart** 2020-12-19 12:06 UTC
