### ISSUE TITLE
Unable to cast transparent proxy to type 'Machine.VSTestAdapter.Discovery.BuiltIn.TestDiscoverer'

### ISSUE THREAD

**Issue by Aequitatis** [machine/machine.specifications#379] opened 2019-04-12 09:42 UTC
I recently upgraded to VS 2019.  Since Resharper is slow to upgrade, I am attempting to use the VS test adapter.  When I add the nuget package in and at take a look at the discovered tests, none of the mspec ones are there.  Upon examining the logs I can see the below logs.

We are running .Net Framework 4.6.1.

[12/04/2019 10:34:07 Informational] ------ Discover test started ------
[12/04/2019 10:34:07 Informational] Machine Specifications Visual Studio Test Adapter - Discovering Specifications.
[12/04/2019 10:34:07 Informational] Machine Specifications Visual Studio Test Adapter - Discovering...looking in <File path>.dll
[12/04/2019 10:34:07 Error] Machine Specifications Visual Studio Test Adapter - Error while discovering specifications in assembly <File path>.dll - Unable to cast transparent proxy to type 'Machine.VSTestAdapter.Discovery.BuiltIn.TestDiscoverer'.
[12/04/2019 10:34:07 Informational] Machine Specifications Visual Studio Test Adapter - Discovery Complete - 0 specifications in 1 of 1 assemblies scanned.
[12/04/2019 10:34:07 Warning] No test is available in <File path>.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
[12/04/2019 10:34:07 Informational] ========== Discover test finished: 0 found (0:00:00.6996032) ==========

Thank you for your attention.

**Comment by robertcoltheart** [comment] 2019-04-12 14:16
Do you have a sample project you can zip and attach for us to investigate?

**Comment by Aequitatis** [comment] 2019-04-12 18:16
Alas I can't, as its confidential work from the office.  If you have a suspicion on where or how something like this could happen, I can see about trying to make a clean and small project demonstrating it.

**Comment by robertcoltheart** [comment] 2019-04-13 11:40
If you could give me some pointers at least? Was it using the new csproj format, or the old style? What versions of the nuget libs are you using? Any other referenced libs that might be related (eg nunit or xunit etc)?

**Comment by robertcoltheart** [comment] 2019-06-12 14:08
Closing as I can't reproduce.

**Closed by robertcoltheart** 2019-06-12 14:08 UTC
Labels: Area: Runner - VS, Type: Bug
