### ISSUE TITLE
Updated Resharper Extension still not compatible with 2022.2?

### ISSUE THREAD

**Issue by rob-mason** [machine/machine.specifications#473] opened 2022-08-03 14:47 UTC
Thanks for the prompt work on updating the extension for the newly released 2022.2, however I've just installed the updated extension and it's still showing as Incompatible. Strange one as previously it wasn't available until you posted the new version a few hours ago.

![Screenshot_1](https://user-images.githubusercontent.com/46508075/182637670-a269b95a-6ac7-4f10-a3e6-353eb915b7e8.png)

**Comment by robertcoltheart** [comment] 2022-08-03 20:57
Sorry to hear that. I'll take a look and see what I can do.

**Comment by rob-mason** [comment] 2022-08-03 21:00
> Sorry to hear that. I'll take a look and see what I can do.

If there's anything I can do to assist you, feel free to let me know.

**Comment by robertcoltheart** [comment] 2022-08-06 12:03
I've taken a look at this, and I've honestly got no idea what the issue could be. I naturally assumed that the Wave version isn't matching the Resharper version, but that isn't the case. Everything seems to be in order that I can tell.

@matkoch Any ideas here? It's super frustrating when I do routine R# updates and stuff like this happens.

**Comment by matkoch** [comment] 2022-08-06 13:19
What is the Wave version specified?

**Comment by robertcoltheart** [comment] 2022-08-06 19:21
@matkoch It's 222.0.0

**Comment by robertcoltheart** [comment] 2022-08-07 11:14
@rob-mason I found a temporary workaround. If you disable the plugin verifier, it seems to work:

![image](https://user-images.githubusercontent.com/13191652/183287916-9619ab40-e7d6-4dbd-ac34-b41cfc029e55.png)

**Comment by robertcoltheart** [comment] 2022-08-08 03:57
I've looked at the R# installation logs and I _think_ it's because the extension verifier in R# is being too aggressive. MSpec uses late-binding to load and execute the runner, and R# extension verifier doesn't like this apparently. Workaround is to disable the verifier, as above. If late-bound references are indeed the cause of this issue, then this is a much bigger fix. 

If the workaround above stops working, I'm tempted to abandon R# integration altogether. JetBrains really doesn't make it easy for plugin developers, and the amount of time I've spent on R# integration vs the rest of the framework is way out of proportion.

**Comment by rob-mason** [comment] 2022-08-09 09:05
> @rob-mason I found a temporary workaround. If you disable the plugin verifier, it seems to work:
> 
> ![image](https://user-images.githubusercontent.com/13191652/183287916-9619ab40-e7d6-4dbd-ac34-b41cfc029e55.png)

Thanks for looking into this (not so simple issue!) and for coming up with a quick workaround. I've just tested switching off verification and it's now working again. 

Cheers @robertcoltheart for your assistance, and hard work on supporting 3 version of Resharper and Rider each and every year, it's appreciated.

**Comment by matkoch** [comment] 2022-08-09 13:53
Hi @robertcoltheart,

I can very much relate to how challenging it is to keep plugins up-to-date. I've been in the very same situation as you before joining the JetBrains team. Funnily, not a lot has changed in those regards since then 🤭 I have about 10 plugins and often have to ping people. For external plugin authors, we have a private Slack channel that I would be happy to invite you to. Every non-trivial question can go there, and we are usually very prompt in helping to solve it and also do pull-requests where it makes sense.

I appreciate it very much that you're taking the time to keep this updated. My first plugin was also about test framework integration. This is probably one of the most difficult integration points in the whole SDK. Please, always let me know if there's something I can help with besides the usual "increase dependency version" (which paradoxically should be solved by the verifier 😅).

I will also keep you posted while our developers are investigating the issue. Without going into too much detail for now, it's somehow related to the `mscorlib` reference.

**Comment by robertcoltheart** [comment] 2022-08-09 20:45
Thanks @matkoch. As I stated in the other post, the issue is that the test adapter needs to target both netframework and netstandard. This is how the xUnit adapter for R# works.  The Resharper.SDK package only targets netframework, so I can't use that. I've been using the Resharper.UnitTesting.Abstractions package, which is unlisted on Nuget but has the types I need for the test adapter. I can't bundle this dll with the plugin since it's provided by Resharper. Hence why I think the extension verifier is complaining, because there's a missing dll reference.

**Comment by mikeblakeuk** [comment] 2022-08-18 15:44
Any ideas?

**Comment by robertcoltheart** [comment] 2022-08-19 00:30
It's with JetBrains now. There is an update coming with `2022.2.2` with _may_ solve this issue.

**Comment by robertcoltheart** [comment] 2022-08-23 02:12
This issue _should_ be fixed with the latest release. Please let me know if it's not the case and I'll reopen this issue.

**Closed by robertcoltheart** 2022-08-23 02:12 UTC
Labels: Area: Runner - R#, Type: Bug
